{% set name = "datacube" %}
{% set version = "1.8.8" %}
{% set sha256 = "e4f6cc2d5142b83e5b5d782c0eb3d437e85dc31a45ebfd96a43eee598a9f225b" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 1
  noarch: python
  entry_points:
    - datacube = datacube.scripts.cli_app:cli
    - datacube-search = datacube.scripts.search_tool:cli
    - datacube-worker = datacube.execution.worker:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.8
    - setuptools
    - setuptools_scm >=3.4
    - toml
  run:
    - python >=3.8
    - affine
    - botocore
    - boto3
    - cachetools
    - click >=5.0
    - cloudpickle >=0.4
    - dask-core
    - distributed
    - pyproj >=2.5
    - shapely >=1.6.4
    - jsonschema
    - lark
    - netcdf4
    - numpy
    - pandas
    - psycopg2
    - python-dateutil
    - pyyaml
    - rasterio >=1.3.2
    - sqlalchemy
    - geoalchemy2
    - xarray >=0.9,!=2022.6.0
    - toolz


test:
  imports:
    - datacube
    - datacube.api
    - datacube.drivers
    - datacube.drivers.netcdf
    - datacube.drivers.postgres
    - datacube.execution
    - datacube.index
    - datacube.model
    - datacube.scripts
    - datacube.storage
    - datacube.testutils
    - datacube.ui
    - datacube.utils
    - datacube.utils.aws
  commands:
    - pip check
    - datacube --help
    - datacube-search --help
    - datacube-worker --help
  requires:
    - pip

about:
  home: http://www.opendatacube.org
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: Data analysis environment for earth observation data
  description: |
    Open Data Cube Core provides an integrated gridded data analysis environment
    for decades of analysis ready earth observation satellite and related data
    from multiple satellite and other acquisition systems.
  doc_url: http://datacube-core.readthedocs.io
  dev_url: https://github.com/opendatacube/datacube-core

extra:
  recipe-maintainers:
    - andrewdhicks
    - GypsyBojangles
    - jeremyh
    - Kirill888
    - omad
    - snowman2
