{% set name = "datacube" %}
{% set version = "1.8.7" %}
{% set sha256 = "ed90d171d53938217091e5ce256172090b71645a82751c79c4b4c721fa4065fc" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: python
  entry_points:
    - datacube = datacube.scripts.cli_app:cli
    - datacube-search = datacube.scripts.search_tool:cli
    - datacube-worker = datacube.execution.worker:main

requirements:
  host:
    - pip
    - python >=3.6
    - setuptools
    - setuptools_scm >=3.4
    - toml
    - pytest-runner
    - sphinx
    - sphinx-click
    - click
  run:
    - python >=3.6
    - affine
    - botocore
    - boto3
    - cachetools
    - click
    - cloudpickle >=0.4.0
    - dask
    - pyproj
    - shapely
    - jsonschema
    - lark-parser
    - netcdf4
    - numpy
    - pandas
    - psycopg2
    - python-dateutil
    - pyyaml
    - rasterio >=1.0.2
    - sqlalchemy
    - xarray >=0.9
    - toolz


test:
  imports:
    - datacube
    - datacube.api
    - datacube.drivers
    - datacube.drivers.netcdf
    - datacube.drivers.postgres
    - datacube.execution
    - datacube.index
    - datacube.model
    - datacube.scripts
    - datacube.storage
    - datacube.testutils
    - datacube.ui
    - datacube.utils
    - datacube.utils.aws
  commands:
    - datacube --help
    - datacube-search --help
    - datacube-worker --help
# The following may be required if we start actually running our tests.
# For now, we're just testing that everything seems to have built okay
#  requires:
#    - compliance-checker
#    - hypothesis
#    - mock
#    - pycodestyle
#    - pylint
#    - pytest
#    - pytest-cov
#    - pytest-timeout

about:
  home: http://www.opendatacube.org
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: Data analysis environment for earth observation data
  description: |
    Open Data Cube Core provides an integrated gridded data analysis environment
    for decades of analysis ready earth observation satellite and related data
    from multiple satellite and other acquisition systems.
  doc_url: http://datacube-core.readthedocs.io
  dev_url: https://github.com/opendatacube/datacube-core

extra:
  recipe-maintainers:
    - andrewdhicks
    - GypsyBojangles
    - jeremyh
    - Kirill888
    - omad
    - snowman2
