travis:
  secure:
    BINSTAR_TOKEN: XS7Igpc7mO4VjsTOAAs9V59pBvPfOkSxvyZ9hO8mdCHtqmAJkOtqkSUUcbUoTgt/qN/wWmg9lcN0vjqBMMk1I02IgEfuaK4J3Y6m5fnCzkEKc8uXu3erYwcLsgYhNFDQFbBQZKSkRASRyRwxhDBkVV2+V9z4hpjBpmP2umO+tEk+dOCGsq0PLol0ZqJY3a9XTlGm886OvbUHAkKceWNq2p72hnE8LyPUkYyBP5B1Fj/rkST2eA3X5dwSzFycxsH9zr7X/C4zdZX+h7A2H4pzCKRxIWzOAnF5Et4Qp//2jpF9wRxuJnpQAZ2Qeb4Q7N60ywYq1T7QQVVjZfDu8TRZJAn6k91bMJbF61vmMJGQJXQLJsmx05YQfKgXFTjaZBQWA5zG4YBO/bwRxT21QeOwvh+8JZGLUaDi1ccHhw3tI5kysYvLT9KlwdIaE1sq47PffSNQT84exAIFR0DtRGlXA6STEBzyl/gD6+3yYYSL69XflZc1fCqy8dqqaYZNciVLg2PflPxBGqVz3PRWAj/w15mpgqV9lqpTGIzr65HgdG97mNKvqu7kPk5eqsB+WZQXrldAv66XVT1ZKFEJVQAs5Dk908tw6KFmRKQs3siCA5SqESKkbG64AwF5L97jUO/gBMMIB9/VsT5pfXH+DT67Xy+G9kSVJbL1sTTa/In1dgw=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
