travis:
  secure:
    BINSTAR_TOKEN: XgEzB+51PcR8HYrk2+Nak/FxGGO8ROjQ4X1QClUI3RoaJy427/r7MXG1IhuIeVCWzZ/I5Rdu98FXvzCvEDNWQo7qmXztkb5PWz+r5bDD+VWW9SkLXzc2gIXTJ0hZxUjo3OhDk+6+bFpuXpifihsF6ztkyH3aTYd4cYt6pesOB35oqw/yYlCIi2iaJV0u1OFQJjCEHqMRGXWRW+CPB6yFQr/O97f22hGXpHeHyySsPgNZ2bbKnOrGQQY0qDg4MIX6wAjCEgtPiGZ11WhiCRwanRgu4DV25dNPN0Bu8lipqEjoAmXXPij9YaqEwt/Z5wAXh90ZFFhlI8LWiKG1nZ4GJGJHXdzNWrfgq5mRcy9Wf+uijNL+hRWKaZ9D6v1XAMJ6c98uvBJWpjD7O6d6jstjEuaOA86+P4gm05/Wrd+ifCrdKu5E5/PP3Ca8r2KG+/yqwvU/zvkhVO2G5jCSAxAwcr919GVVhsrFfzIpF/B5pQEeHbJBxO17OCxgH9QbgcuUMeTqGnfKb0dCWH0BnvipZw/Du+zbWEIc1ojMH2qhfwMJbrPIda5WzDqZocCt6GCEDsM3QzsBPN2IRJf6Ln+ymhXSDM7PIEP6FTqs9fpp3qOoHEmU+cGCSzx/EarfvG7qEG6Lnh40071U/Kxx2NIQS5q+JYNhhUn4QvqHk5LxJzo=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
